# travis.yml for github.com/jts/nanopolish

language: cpp

# Install and export newer gcc
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8

script: make CXX=g++-4.8 nanopolish && make CXX=g++-4.8 test
